parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"
rules:
  indent: ["error", 2]
  "@typescript-eslint/ban-ts-comment": 0
  "@typescript-eslint/no-explicit-any": 0
ignorePatterns:
  - "node_modules/**/*"
  - "dist/**/*"
  - "test/**/*"
settings:
  import/resolver:
    alias:
      map:
        - ["@", "./"]
      extensions: [".ts", ".js"]
