version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: auction_house
    command: postgres -i -h *